name: ExemplePlugin
version: '${project.version}'
main: fr.robie.exempleplugin.ExemplePlugin
description: Exemple plugin to use dispatch command lib
api-version: '1.21'
bootstrapper: fr.robie.exempleplugin.ExemplePluginBootstrap
loader: fr.robie.exempleplugin.ExemplePluginLoader